### ISSUE TITLE
An import error for hdlConvertor/tests/test_verilog_conversion.py

### ISSUE THREAD

**Issue by lionheart117** [Nic30/hdlConvertor#124]
https://github.com/Nic30/hdlConvertor/blob/3372b2dd6e4366ae8e44fcbf529c62ca230a9afe/tests/test_verilog_conversion.py#L8

lionheart117@Lionheart-PC:~/project/hdlConvertor/tests$ python3 -u "/home/lionheart117/project/hdlConvertor/tests/test_verilog_conversion.py"
Traceback (most recent call last):
  File "/home/lionheart117/project/hdlConvertor/tests/test_verilog_conversion.py", line 8, in <module>
    from tests.hdl_parse_tc import TEST_DIR, HdlParseTC, parseFile
ModuleNotFoundError: No module named 'tests.hdl_parse_tc'

**Comment by Nic30** [comment]
3ade93e5dbe2e96bb23349781f141f70c0b1e9ad
