### ISSUE TITLE
A humble request

### ISSUE THREAD

**Issue by mohit162009** [Nic30/hdlConvertor#13]
Hello Nic,

I have a humble request, Could you please remove the examples you have added in the tests, I am not supposed to share such information, I can get in serious trouble. I am very sorry for the inconvenience and thanks a lot for your fixes and help.

**Comment by Nic30** [comment]
Hello mohit162009,
I will remove it, but are you sure? There is nothing in package example just an array of 0 constants?
Do you mean package example or different file?

**Comment by mohit162009** [comment]
Hello , Thanks a lot Nic! Yes these two files :+1: 
![image](https://user-images.githubusercontent.com/30684610/36836182-ae9c366e-1d5e-11e8-97c2-a99b4deee49e.png)

These files contains confidential information.

**Comment by Nic30** [comment]
It is removed.
