### ISSUE TITLE
appveyor ci tests for windows

### ISSUE THREAD

**Issue by Nic30** [Nic30/hdlConvertor#24]

**Comment by Nic30** [comment]
ci tests set, but not passing due ANTLR dll exports

**Comment by Thomasb81** [comment]
It seems an additional optional `/bigobj` option is required for MSVS2017. Extract from the logof the build system:
`[00:03:34] C:\projects\hdlconvertor\src\svConverter\sv2012Parser\sv2012Parser.cpp : fatal error C1128: number of sections exceeded object file format limit: compile with /bigobj`

**Comment by Thomasb81** [comment]
Or may be a define need to be setup to control the compilation of the sv part. Since it is today not usable.

**Comment by Nic30** [comment]
Now compiles and fails while linking. https://ci.appveyor.com/project/nic30/hdlconvertor/builds/23688911
This errors are also related to vpp, as a msvc is what it is I will rather wait on vpp and then solve the rest of errors so I do not have to go trough same hell twice.

**Comment by Nic30** [comment]
c1f8171f8049550824707a752a1ed68c30b7721c compiles and tests are passing
